In [4]:
import random
import numpy as np
import pandas as pd

with open("names.txt",encoding="utf-8") as file:
    content = file.read()

names_list = content.split()
names = random.choices(names_list,k=50)

with open("names.txt",encoding="utf-8") as file:
    content = file.read()
    
scores = np.random.randint(50,101,size=(50,5))
student_df = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index=names)
student_df

      國文   英文   數學  地理   歷史
姜琬婷   65   79   67  95   68
沈心利   80   68   97  66   55
黃靜怡   51   73   98  84   76
林建宏   83   56   95  90   65
黃淑芬   88   74   72  75   60
謝南慧   59   51   51  83   81
郭坤花   79   59   80  93   55
唐雪豪   75   53   90  59   50
王筱婷   86   78   73  86   58
林淑安   68   83   98  92   90
郭舜昇   68   88   67  97   72
林淑安   96   60   71  71   57
陳怡珊   51   74   97  69   75
游一鈺   57   51   69  76   61
陳筱涵   97   71   83  62   58
陳淑娟   53   56   86  77   74
馮芳如   91   92   73  62   84
趙偉銘   89   94   85  90   92
陳怡容   51   77   80  76   74
林瑞喬   68   72   70  50   71
陳淑娟   65   71   64  69   67
陳怡珊   69   95   64  55   90
陳冠竹   72  100   61  76   65
金宜芳   74   65   62  72   88
程玫靖   77   87   64  68   91
林冠蕙   96   85   85  90   52
杜明延   91   80   77  82   57
郭坤花   85   83   96  70   96
陳怡伶   58   98   67  86   84
杜明延   94   63   95  83   71
王筱婷  100   86   57  66   99
張伊映   96   63   53  58   74
陳姵彬   63   62   65  84   90
林康亮   69   64   55  73   72
馮芳如   94   79   89  57  100
郭坤花   74   71  100  68   99
劉昀天   65   54   52  69   96
郭致恬   63   64   78  71   96
朱惠儀   67   90   53  81   65
陳慧君   89   73   74  66   82
胡姿婷   80   67   65  52   53
陳怡容   75   57   84  57   97
朱彥志   61   98   53  70   79
陳文賢   72   63   55  63   94
蕭淑華   52   81   60  70   68
郭致恬   90   61   77  92   56
王品星   90   56   55  77   80
陳怡容   73   93   95  93   98
陳嘉淑   74   85   82  69   83
鞠冠宇   93   64   95  59   58

In [2]:
student_df['國文']
student_df[['國文','英文']]

      國文   英文
李進慧   93   67
楊健麟   63   62
賴佳雯   77   80
王明昇   94   65
劉雯芬   63  100
周家銘   52   84
黃佩玲   65   53
楊火帆   60   69
葉軍仰   90   54
陳倩妮   90   76
黃江旭   86   67
蘇婷婷   72   87
崔孝憲   94   54
林向鈺   79   71
元延辛   59   75
杜儀鳳   55   78
黃心航   63   92
黃彥孝   54   96
林淑安   81   81
陳逸凡   50   97
吳柏誠   81   89
林康亮   89   78
吳孟穎   96   91
林康亮   80   88
傅佳琳   74   50
王怡君   76   67
王惠皓   68   56
羅佩樺  100   75
林康亮  100   89
臧怡君   94   73
王孝純   63  100
劉耿琦   67   93
呂傑宣   75   60
龐皓芳   54   91
游詩亞   57   58
楊韻如   55   77
王筱婷   74   69
魏秋萍   50   83
陳信宏   94   50
黃佩玲   96   98
楊又源   93   64
楊建安   56   92
楊綺芬   80   90
黃心航   67  100
鄧淑娟   95   99
龐皓芳   69   81
翁羽威   50   75
陳得映   98   89
謝水儒   96   95
張伊映   65  100

In [7]:
student_df.loc['張伊映']

國文    96
英文    63
數學    53
地理    58
歷史    74
Name: 張伊映, dtype: int64

In [6]:
student_df.iloc[0]
student_df.iloc[[0,49]]
student_df.iloc[:5]
student_df.iloc[-5:]

     國文  英文  數學  地理  歷史
郭致恬  90  61  77  92  56
王品星  90  56  55  77  80
陳怡容  73  93  95  93  98
陳嘉淑  74  85  82  69  83
鞠冠宇  93  64  95  59  58

In [8]:
student_df.iloc[-5:,:3]

     國文  英文  數學
郭致恬  90  61  77
王品星  90  56  55
陳怡容  73  93  95
陳嘉淑  74  85  82
鞠冠宇  93  64  95

In [10]:
student_df['地理']<60

姜琬婷    False
沈心利    False
黃靜怡    False
林建宏    False
黃淑芬    False
謝南慧    False
郭坤花    False
唐雪豪     True
王筱婷    False
林淑安    False
郭舜昇    False
林淑安    False
陳怡珊    False
游一鈺    False
陳筱涵    False
陳淑娟    False
馮芳如    False
趙偉銘    False
陳怡容    False
林瑞喬     True
陳淑娟    False
陳怡珊     True
陳冠竹    False
金宜芳    False
程玫靖    False
林冠蕙    False
杜明延    False
郭坤花    False
陳怡伶    False
杜明延    False
王筱婷    False
張伊映     True
陳姵彬    False
林康亮    False
馮芳如     True
郭坤花    False
劉昀天    False
郭致恬    False
朱惠儀    False
陳慧君    False
胡姿婷     True
陳怡容     True
朱彥志    False
陳文賢    False
蕭淑華    False
郭致恬    False
王品星    False
陳怡容    False
陳嘉淑    False
鞠冠宇     True
Name: 地理, dtype: bool

In [11]:
#值的選取
student_df[student_df['地理']<60]

     國文  英文  數學  地理   歷史
唐雪豪  75  53  90  59   50
林瑞喬  68  72  70  50   71
陳怡珊  69  95  64  55   90
張伊映  96  63  53  58   74
馮芳如  94  79  89  57  100
胡姿婷  80  67  65  52   53
陳怡容  75  57  84  57   97
鞠冠宇  93  64  95  59   58

In [13]:
#地理和國文同時不及格的
student_df[(student_df['地理'] < 60) & (student_df['國文'] < 60)]

Empty DataFrame
Columns: [國文, 英文, 數學, 地理, 歷史]
Index: []

In [14]:
#地理和國文同時不及格的
student_df[(student_df['地理'] < 60) | (student_df['國文'] < 60)]

     國文  英文  數學  地理   歷史
黃靜怡  51  73  98  84   76
謝南慧  59  51  51  83   81
唐雪豪  75  53  90  59   50
陳怡珊  51  74  97  69   75
游一鈺  57  51  69  76   61
陳淑娟  53  56  86  77   74
陳怡容  51  77  80  76   74
林瑞喬  68  72  70  50   71
陳怡珊  69  95  64  55   90
陳怡伶  58  98  67  86   84
張伊映  96  63  53  58   74
馮芳如  94  79  89  57  100
胡姿婷  80  67  65  52   53
陳怡容  75  57  84  57   97
蕭淑華  52  81  60  70   68
鞠冠宇  93  64  95  59   58